"""Sesame hardware simulation and firmware emulation environment."""

from .mcu import CortexM4Emulator
from .device_firmware import (
    SimulatedFirmwareDevice,
    SimulatedSesameLock,
    SimulatedSesame6Pro,
    SimulatedSesame6,
    SimulatedSesame6ProSlidingDoor,
    SimulatedSesame5,
    SimulatedSesame5Pro,
    SimulatedSesame5USA,
    SimulatedSesameBike2,
    SimulatedSesameBike3,
    SimulatedSesameKeypad,
    SimulatedSesameTouch,
    SimulatedSesameTouchPro,
    SimulatedSesameTouch2,
    SimulatedSesameTouch2Pro,
    SimulatedSesameFace,
    SimulatedSesameFacePro,
    SimulatedSesameFaceAI,
    SimulatedSesameFaceProAI,
    SimulatedSesameFace2,
    SimulatedSesameFace2Pro,
    SimulatedSesameFace2AI,
)
from .ble_bridge import VirtualBleakClient, VirtualBleakScanner, VirtualBLEDevice

__all__ = [
    "CortexM4Emulator",
    "SimulatedFirmwareDevice",
    "SimulatedSesameLock",
    "SimulatedSesame6Pro",
    "SimulatedSesame6",
    "SimulatedSesame6ProSlidingDoor",
    "SimulatedSesame5",
    "SimulatedSesame5Pro",
    "SimulatedSesame5USA",
    "SimulatedSesameBike2",
    "SimulatedSesameBike3",
    "SimulatedSesameKeypad",
    "SimulatedSesameTouch",
    "SimulatedSesameTouchPro",
    "SimulatedSesameTouch2",
    "SimulatedSesameTouch2Pro",
    "SimulatedSesameFace",
    "SimulatedSesameFacePro",
    "SimulatedSesameFaceAI",
    "SimulatedSesameFaceProAI",
    "SimulatedSesameFace2",
    "SimulatedSesameFace2Pro",
    "SimulatedSesameFace2AI",
    "VirtualBleakClient",
    "VirtualBleakScanner",
    "VirtualBLEDevice",
]

